import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';

import { format } from 'prettier';

const inputs = [
  {
    file: 'hyph-ru.tex',
    name: 'ru',
    hash: 'ce988fcc66e5e29d7474df5ab5b489d3f52a50ebccf570997f992d84221b922a',
    bytes: 68421,
  },
  {
    file: 'hyph-en-us.tex',
    name: 'en-us',
    hash: 'f4ffcd96c5cbc886bdad23f95dcae8edc3cd3620eae62f7946eceda97c4e68f8',
    bytes: 34128,
  },
];
const packageRoot = new URL('../../packages/typographist/', import.meta.url);

const extractBlock = (source: string, command: string) => {
  const blocks = Array.from(source.matchAll(new RegExp(String.raw`\\${command}\s*\{([^{}]*)\}`, 'gu')));
  const block = blocks[0]?.[1];
  if (blocks.length !== 1 || block === undefined || /[\\{}]/u.test(block)) {
    throw new TypeError(`Expected one plain ${command} block`);
  }
  return block.trim().split(/\s+/u);
};

for (const input of inputs) {
  const bytes = await readFile(new URL(`pattern-data/${input.file}`, packageRoot));
  if (bytes.length !== input.bytes || createHash('sha256').update(bytes).digest('hex') !== input.hash) {
    throw new Error(`Pinned source checksum or byte length mismatch: ${input.file}`);
  }

  const source = new TextDecoder('utf-8', { fatal: true }).decode(bytes).replace(/%[^\n]*/gu, '');
  const patterns = extractBlock(source, 'patterns');
  const entries = extractBlock(source, 'hyphenation');
  const exceptions = entries.map((entry) => {
    if (!/^[\p{L}]+(?:-[\p{L}]+)*$/u.test(entry)) {
      throw new TypeError(`Unsupported source exception syntax: ${input.file}`);
    }
    const positions: number[] = [];
    let word = '';
    for (const symbol of entry) {
      if (symbol === '-') {
        positions.push(word.length);
      } else {
        word += symbol;
      }
    }
    return { word, positions };
  });

  const generated = `// Generated by tools/pattern-data/convert-patterns.ts. Source notices: ../../../pattern-data/${input.file}.
export const patterns = Object.freeze(${JSON.stringify(patterns)});
export const exceptions = Object.freeze([${exceptions.map(({ word, positions }) => `Object.freeze({ word: ${JSON.stringify(word)}, positions: Object.freeze(${JSON.stringify(positions)}) })`).join(',')}]);
`;
  await writeFile(
    new URL(`src/languages/bundled/${input.name}-data.constants.ts`, packageRoot),
    await format(generated, { parser: 'typescript', singleQuote: true, printWidth: 120, trailingComma: 'all' }),
  );
  console.log(
    `${input.file}: ${String(patterns.length)} patterns, ${String(exceptions.length)} exceptions (${String(exceptions.filter(({ positions }) => positions.length === 0).length)} no-break)`,
  );
}
