import type { parseTexRules } from '@/tex/parse-tex-rules.util.js';

const quote = (value: string) => `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;

export const renderRules = (rules: ReturnType<typeof parseTexRules>) => {
  const notices = rules.notices.map((notice) => `// ${notice}`).join('\n');
  const patterns = rules.patterns.map((pattern) => `  ${quote(pattern)},`).join('\n');
  const exceptions = rules.exceptions
    .map(
      ({ word, positions }) =>
        `  Object.freeze({ word: ${quote(word)}, positions: Object.freeze([${positions.join(', ')}]) }),`,
    )
    .join('\n');

  return `// Generated by transform-rules. Source comments follow.\n${notices}\nexport const patterns = Object.freeze([\n${patterns}\n]);\nexport const exceptions = Object.freeze([\n${exceptions}\n]);\n`;
};
